apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-config
  namespace: infrastructure-qa-orion
data:
  config: |
    [default]
    region = us-west-2
    output = json
    [profile qa]
    region = us-west-2
  credentials: |
    [qa]
    aws_access_key_id = ${AWS_ACCESS_KEY_ID}
    aws_secret_access_key = ${AWS_SECRET_ACCESS_KEY}
    aws_session_token = ${AWS_SESSION_TOKEN} 